# -*- mode: ruby -*-
# vi: set ft=ruby :

# https://codeblog.dotsandbrackets.com/vagrant-windows/

Vagrant.configure("2") do |config|

  config.vm.box = "win10"

  config.vm.communicator = "winrm"
  config.winrm.username = "IEUser"
  config.winrm.password = "Passw0rd!"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  
  config.vm.synced_folder "data/", "/vagrant", create: true

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  #
  # https://www.vagrantup.com/docs/providers/virtualbox/configuration

  config.vm.provider "virtualbox" do |vb|
    #vb.name = "vagrant-win10"
    
    # https://www.virtualbox.org/manual/ch08.html
    #vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
    vb.customize ["setextradata", :id, "GUI/MaxGuestResolution", "any"]
    vb.customize ["setextradata", :id, "custom3k", "2880x1620x32"]
    #vb.customize ["controlvm", :id, "setvideomodehint", "2880", "1620", "32"]

    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    # Customize the amount of memory on the VM:
    vb.memory = 8192
  end
  
  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  
  config.vm.provision "shell", privileged:true, inline: <<-SHELL

  dir C:/vagrant/

    echo $(Get-Date)
    echo $(Get-Date) >> C:/vagrant/v-log.txt

  SHELL
end
